apiVersion: v1
kind: Pod
metadata:
  name: example-data-tier
  labels: 
    app: example
    tier: data
spec: 
  containers:
    - name: redis
      image: "redis:latest"
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 6379
          protocol: TCP