apiVersion: v1
kind: Pod
metadata: 
  name: hello-world
  labels:
    app: hello-world
spec:
  containers:
    - name: server
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP		
