apiVersion: v1
kind: Pod
metadata: 
  name: example
  labels:
    name: example
spec:
  containers:
    - name: redis
      image: "redis:latest"
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 6379
          protocol: TCP		
    - name: server
      image: "slashdeploy/microservice-example:server-v1"
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
        - name: "REDIS_URL"
          value: "redis://localhost:6379"	

    - name: counter
      image: "slashdeploy/microservice-example:counter-v1"
      env: 
        - name: "API_URL"
          value: "http://localhost:8080"		  

    - name: poller
      image: "slashdeploy/microservice-example:poller-v1"
      env: 
        - name: "API_URL"
          value: "http://localhost:8080"