apiVersion: v1
kind: Pod
metadata:
  name: example
  labels: 
    app: example
spec:
  containers:
    - name: server
      image: nginx:latest
      ports:
        - containerPort: 80
          protocol: TCP
      env: 
        - name: API_KEY_1
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: key1
        - name: API_KEY_2
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: key2
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: example
              key: common.log_level
        - name: STAGE
          valueFrom:
            configMapKeyRef:
              name: example
              key: common.stage